### ISSUE TITLE
Get woocommerce_rest_authentication_error when try autenticate from HTTP 

### ISSUE THREAD

**Issue by limaku** [XiaoFaye/WooCommerce.NET#111]
Hi Xiao! i dont authenticate with the last version of WooCommerce.NET 

The server response 

{"code":"woocommerce_rest_authentication_error","message":"Firma no v\u00e1lida - la firma proporcionada no coincide.","data":{"status":401}}

i try to connect from Argentine. The timestamp generate a problem? Do you have a idea?

**Comment by david-cooper** [comment]
Hi,
I believe I'm experiencing a similar issue. I'm using the latest version of WooCommerce.NET and an HTTP API address - which is purposely running an older version of WooCommerce to access the Legacy v3 API. 
Note: This problem doesn't seem to occur for the latest v2 WooCommerce API.

I am attempting to access a list of orders using the "GetOrders" call and using the "updated_at_min" filter.
If I pass null through to the parameters dictionary when calling GetOrders - everything seems to work fine and the API returns all of the WooCommerce orders.
If I pass a parameters dictionary through with "filter[updated_at_min]" as the key then my GetOrders task results in a 401 Unauthorised error with the following message:
{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}

It doesn't seem to matter what dictionary key I pass through, nor what DateTime string is passed into the dictionary value.

Here's an example:
![image](https://cloud.githubusercontent.com/assets/12811499/25376026/a465ba5c-299a-11e7-9a6a-bef1f34806ae.png)

**Comment by kurtgronbech** [comment]
I also got this error when trying to use "filter[sku]" on GetProducts. The problem was this line in function GetOAuthEndPoint in RestAPI.cs. 

stringToSign += parm.Key + "%3D" + Uri.EscapeDataString(Uri.EscapeDataString(parm.Value)) + "%26";

We also need to encode parm.Key because of the brackets in the filter string. This worked for me: 

stringToSign += Uri.EscapeDataString(Uri.EscapeDataString(parm.Key)) + "%3D" + Uri.EscapeDataString(Uri.EscapeDataString(parm.Value)) + "%26";

**Comment by XiaoFaye** [comment]
Hi @kurtgronbech , I'm not getting any error on v1 & v2 api, can you provide more details?

![image](https://cloud.githubusercontent.com/assets/6334728/26083629/1000c52c-3a2b-11e7-90b8-29d6228eabbd.png)

**Comment by kurtgronbech** [comment]
Sure. The problem only manifests itself when using filter parameters using brackets, such as: 

filter[created_at_min]=2013-11-01
filter[sku]=1234

Dictionary<string, string> parms = new Dictionary<string, string>(); 
parms.Add("filter[sku]", sku); // filter with brackets! 

var wooProducts = wc.GetProducts(parms)

Because the code in GetOAuthEndPoint is not escaping the parm.Key we'll get an authentication error because of the brackets in the filter parameter(s).

**Comment by XiaoFaye** [comment]
@kurtgronbech , I'm sure that you are using the legacy v3, which uses filter as parameter, the latest rest api version will not have this problem as it doesn't use filter with brackets anymore.

**Comment by kurtgronbech** [comment]
@XiaoFaye Yes, I'm using the legacy v3 api. And all is good for me after fixing the encoding of parm.Key.

**Comment by XiaoFaye** [comment]
@kurtgronbech this has been fixed in the latest commit.

**Comment by jblanc77** [comment]
I'm also getting this response error: {"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}

I'm using the code from the example:
                RestAPI rest = new RestAPI("http://www.website.com/wp-json/wc/v2/", "xxx", "xxx");
                WCObject wc = new WCObject(rest);
                var result = System.Threading.Tasks.Task.Run(async () => await wc.Order.GetAll());
                var wcOrders = result.Result;
