### ISSUE TITLE
Insert new Meta Data on order_meta

### ISSUE THREAD

**Issue by dimram** [XiaoFaye/WooCommerce.NET#180]
Hi,
I am trying to create a new meta data on order_meta. But i don't really know how to do it because i don't want to replace an existing one but to create it...
When i tries to update the order status (that already exists) works fine.... But not working when i am trying toi create a new meta key with name checkedit and value yes.
Here is my code
  wc.UpdateOrder(36, new Order { order_meta = {checkedit = "yes" } });

Thanks in advance ..

**Comment by Magnetize** [comment]
Hi there!
I am also updating custom meta data on orders, and I am doing it like this since the Woo 3.0 update.

`Order order = new Order();
 List<OrderMeta> metaList = new List<OrderMeta>();
 var meta = new OrderMeta();
 meta.key = metaField;
 meta.value = metaValue;
 metaList.Add(meta);
 order.meta_data = metaList;
`
Then I update the order like you are doing.
Maybe try this out. :)

**Comment by dimram** [comment]
Thanks it worked fine.. But i tried to access the key after that and i cannot access it...
I cann see the key on the order on Woocommerce as custom field but i cannot access it.
I am using this code 

```
 Order order = await wc.GetOrder((int)result["id"]);

 if (order.order_meta.ContainsKey("checkedit") )
   {

}
```

The problem is on the if statement
I am getting this error
`An exception of type 'System.NullReferenceException' occurred in 
`

**Comment by Magnetize** [comment]
Hm, is your order object NULL above? What is the value of result["id"] ?
I tried getting an order here and I get 5 meta fields in the meta_data section of the order, as expected.
