### ISSUE TITLE
How to Delete Images\Gallery when delete product?

### ISSUE THREAD

**Issue by vadimneta** [XiaoFaye/WooCommerce.NET#337]
**How to Delete Images\Gallery when deleting product?**

- **Wordpress version**: latest

**How to Delete Images\Gallery when deleting product?**

for example:
`   await wc.Product.Delete(100);`

**Comment by XiaoFaye** [comment]
Wordpress doesn't do that by default, you will need to do some customize work.

**Comment by vadimneta** [comment]
Hello,
Thanks,
I have another question,
**How to Add a new Product with Existing Image In WordPress?**

I didn't find how to Add product with Existing Image (By Adding or Relate ImageId or ImageName to the Product object)
In case of it is possible, can you give a code example?

Thanks a lot!

**Comment by topherZa** [comment]
If I'm understanding your question correctly, I do this by providing the full image url to the images object

I have a method that builds the url and returns the url of the site which I save for later as there are multiple images for me:

` !string.IsNullOrWhiteSpace(imageUrl) ? $"{_url}{imageUrl}" : "";`

so the Url returned will be something like this example: 

`https://www.mysite.co.za/wp-content/uploads/images/LOUNGE_FURNITURE/LOUNGE_SUITES/MOTION_SUITE/10023251.jpeg`

And then I have the following method which creates List of ProductImage and returns it.
```
public void AddImages(List<ProductImage> images, ImportLine i)
        {
            int cnt = 0;
            List<string> urls = new List<string>()
            {
                i.ImageURL1,
                i.ImageURL2,
                i.ImageURL3,
                i.ImageURL4,
                i.ImageURL5,
                i.ImageURL6
            };
            foreach (var url in urls)
            {
                if (!string.IsNullOrEmpty(url))
                {
                    images.Add(new ProductImage { position = cnt, src = url, alt = i.Name });
                    cnt++;
                }
            }
        }
```

Then just add that list to the images list.

I think this is what you mean by existing images because I don't have any control over images on the server and if the name of the image (e.g "uploads/images/LOUNGE_FURNITURE/LOUNGE_SUITES/MOTION_SUITE/10023251.jpeg") doesn't exist on the server before trying to create the product I get an error from the api.

Hope this helps.

**Comment by sterenas** [comment]
You’ve got a for loop from 0 to 4 and are creating 5 products with the same image. Since the image filename can’t be the same for all 5 products, it’s adding the -x to the name. 
Suggest you try:
- Remove the for loop to create 1 product and check if only 1 image is created
- use different names for the images to make it easier to understand. Create 5 different ones and use them within the for loop to uoload.
Thanks
Sergio

**Comment by vadimneta** [comment]
Hello,
This is a Pseudo-Code I wrote this to illustrate the problem.
When I run a single product with an existing image,
It duplicates the image and does not attach it to a new product.

This is the problem.
Thanks

**Comment by topherZa** [comment]
I have just had a quick look through the [source](https://github.com/woocommerce/woocommerce/blob/3c3894b676f3112db1474a9749f084011eae46d9/includes/api/class-wc-rest-products-controller.php#L228) for the REST API and it looks like if you only give the images' `id` and no `src` for the image that exists for a product, it treats it as an attachment which I think is then the same behavior as choosing an 'attachment ' through the front end when linking existing media to a product. I don't know php so I'm trusting their named functions etc to make my assumption. But have a look and see if you agree. 

After a little googling I've found this: https://developer.wordpress.org/rest-api/reference/media/
I haven't tried it yet but it looks like one might be able to use the standard wordpress API to get the existing media, then you could match it by `src` and just link it by ID. A lot of assumptions here but it feels good to me.

**Comment by vadimneta** [comment]
Hello,
I just try as you suggest with an **id** of mage,
but I get an error:
{"code":"woocommerce_product_image_upload_error","message":"Error getting remote image http:\/\/11262. Error: A valid URL was not provided..","data":{"status":400}}

Anyway thanks a lot for your help.

**Comment by topherZa** [comment]
Hi @vadimneta , I think you have misunderstood. Use the `id` in the `id` param not the `src` param.

I just tried it and successfully linked an existing image to a product using this method, my json was as follows:

```
data = {
    "name": "Premium Quality",
    "type": "simple",
    "regular_price": "21.99",
    "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",

    "images": [
        {
            "id": "64057",
            "position": 0
        }
    ]
}
```

**Comment by vadimneta** [comment]
Hello,
Thanks a lot for your help!!!
It's work as you said by id:
       ```
          //Add Simple Regular Product
                Product simpleProduct = new Product()
                {
                    name = currProd.Title,
                    short_description = currProd.Description,
                    description = currProd.Description,
                    sale_price = Convert.ToDecimal(currProd.SalePrice),
                    regular_price = Convert.ToDecimal(currProd.Price),
                    sku = currProd.Sku;
                    type = "simple",
                    status = "publish",
                    images = new List<ProductImage>()  {
                                        new ProductImage()
                                        {
                                            id = 11262,
                                            alt = currProd.Title,
                                            date_created = DateTime.Now,
                                            date_created_gmt = DateTime.Now,
                                            date_modified = DateTime.Now,
                                            date_modified_gmt = DateTime.Now,
                                            position = 0
                                        }};
                };
              simpleProduct = await wc.Product.Add(simpleProduct);

```
