### ISSUE TITLE
How can I delete shipping line?

### ISSUE THREAD

**Issue by geri1983** [XiaoFaye/WooCommerce.NET#361]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
Wordpress 5.1.1, WooCommerce I think 5.1.1,  v0.7.4
- Steps to replicate the issue

- Details of the error message if there is any

How can I completly delete an order.shipping_line item when updating an order?
My goal is to delete an existing shipping line (for example parcel, with shipping cost), and add a new line, with 0 total value (free shipping)

Thank you

**Comment by XiaoFaye** [comment]
Have you tried `UpdateWithNull(orderid, new { shipping_lines = "" })` ?

**Comment by geri1983** [comment]
Thank you for your quick answer!

If I try with this VB.NET code, it's not working.
Is it the same, that you wrote?

Dim rest As New RestAPI(mvar_P_API_url & "/wp-json/wc/v3/", mvar_P_API_public, mvar_P_API_secret)
Dim wc As New WCObject(rest)

Dim vDic As Dictionary(Of String, String) = New Dictionary(Of String, String)()
vDic.Add("shipping_lines ", "")

Await wc.Order.UpdateWithNull(251, vDic)

**Comment by XiaoFaye** [comment]
The last line should be:

`Await wc.Order.UpdateWithNull(251, New With {Key .shipping_lines = ""})`

**Comment by geri1983** [comment]
After running this code line, the shipping line still exists in the WooCommerce order...
Should this function clear all the shipping lines?

**Comment by XiaoFaye** [comment]
It should, you might need to check with WooCommerce support.

**Comment by dgloveruk** [comment]
Hi Xiao,
I have the same symptom as geri, just updated woocommerce to 3.6.2 but no dice.  I am also using VB .net and the following line :
It behaves as if it does something, no error but nothing happens.
  _Order = Await _wc.Order.UpdateWithNull(OrderID, New With {Key .wpcf_Tracking = Tracking})

Is it because wpcf_Tracking is a field I created as meta data or should it work anyway?

Is there an alternative ?
I have an issue where if I load an order and merely save it back I get an error which blocks any prospect of editing the order.:
e.g If I run in succession :
_Order = Await _wc.Order.Get(OrderID)
_Order = Await _wc.Order.Update(OrderID, _Order)
The get part works, but the update fails with the error below so I really need a way of trying to tweak a value in postmeta.

System.Net.WebException
  HResult=0x80131509
  Message={"code":"rest_invalid_param","message":"Invalid parameter(s): line_items","data":{"status":400,"params":{"line_items":"line_items[0][subtotal] is not of type string."}}}
  Source=WooCommerce.NET
 
Thanks in advance for any suggestions.

**Comment by dgloveruk** [comment]
> It should, you might need to check with WooCommerce support.

Hi Xiao,
I have the same symptom as geri, just updated woocommerce to 3.6.2 but no dice. I am also using VB .net and the following line :
It behaves as if it does something, no error but nothing happens.
_Order = Await _wc.Order.UpdateWithNull(OrderID, New With {Key .wpcf_Tracking = Tracking})

Is it because wpcf_Tracking is a field I created as meta data or should it work anyway?

Is there an alternative ?
I have an issue where if I load an order and merely save it back I get an error which blocks any prospect of editing the order.:
e.g If I run in succession :
_Order = Await _wc.Order.Get(OrderID)
_Order = Await _wc.Order.Update(OrderID, _Order)
The get part works, but the update fails with the error below so I really need a way of trying to tweak a value in postmeta.

System.Net.WebException
HResult=0x80131509
Message={"code":"rest_invalid_param","message":"Invalid parameter(s): line_items","data":{"status":400,"params":{"line_items":"line_items[0][subtotal] is not of type string."}}}
Source=WooCommerce.NET

Thanks in advance for any suggestions.

**Comment by dgloveruk** [comment]
Further to my post I found a solution.  I was able to update data using the following format ``
   x = New OrderMeta
            x.key = "wpcf_Tracking"
            x.value = Tracking
            _Order.meta_data.Add(x)

and to overcome the error that I mentioned above I used 
     _Order.line_items = Nothing
before I updated.
I feared this would blank the line item detail in the existing order but it did not so essentially I have a way now of updating/adding meta via v3 api.
Cheers,
