### ISSUE TITLE
Problem with Getting All Variation with specific Product.

### ISSUE THREAD

**Issue by vishal-parmar** [XiaoFaye/WooCommerce.NET#393]
I'm trying to get  variations of a specific product:

  **var Allvariation = await wc.Product.Variations.GetAll(SpecificProductID)**

but return I am only 10 variation. actually I have 15 variations of this productID. Is there any solution to get all variation?

**Comment by haseebmukhtar** [comment]
Hi
Mostly calls to API returns 10 results only, you need to change the size if you want more than 10.

**Comment by vishal-parmar** [comment]
How I am change the size or get all result of variations with specificif ProductID

**Comment by dnatabar** [comment]
@vishal-parmar 
You can do it with the parms argument.

`            var variations = await wc.Product.Variations.GetAll(prod.id, new Dictionary<string, string>()
            {
                {
                    "per_page", "100"
                }
            });
`
Unsure if there is an upper limit on the "per_page" parameter value, but otherwise you can just ramp it up to `int.MaxValue` i guess,...

**Comment by vishal-parmar** [comment]
@dnatabar Thank you sir
