### ISSUE TITLE
GetAll() Problem

### ISSUE THREAD

**Issue by manossmar** [XiaoFaye/WooCommerce.NET#577]
Hello,

I have a problem getting started with this Nuget.

the problem is with the await operator.
This is a clear and new project just to make some tests.

 please take a look at the attached picture.
Any help will be greatly appreciated

 WooCommerce.NET version 082

-
![Screenshot 2021-03-11 101009](https://user-images.githubusercontent.com/79608308/110755907-297e3c00-8252-11eb-85b7-ac7afe06b2e2.jpg)

**Comment by XiaoFaye** [comment]
try `var products = wc.Product.GetAll().Result;`

**Comment by manossmar** [comment]
Thank you for your prompt reply.
I still get the same message

**Comment by manossmar** [comment]
Actually now I get a runtime error
![Screenshot 2](https://user-images.githubusercontent.com/79608308/110759387-3ac94780-8256-11eb-8ee3-03144dbb0097.jpg)

**Comment by manossmar** [comment]
Never mind that. Everything works ok.
thanks for your great help

**Comment by LetsCNow** [comment]
For the record, afaik, to use await, the function signature needs to be:
public async Task<T> SomeAsyncFuction()

**Comment by gaazkam** [comment]
AFAIK a WPF event handler should be `async void` and then you could `await` within this event handler.

(about the only place where you should use `async void` instead of `async Task`)

So an alternative solution:

```csharp
private async void button1_Click(object sender, EventArgs e)
{
    var products = await wc.Products.GetAll();
    /* ... */
}
```

OP, please be careful with stuff such as `Result`, `Wait`, etc, because they can bite you if you don't know their idiosyncrasies, see for example https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by ColdFire169** [comment]
You'll probably want to read up on asynchronous programming as well.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/
