### ISSUE TITLE
Deserialize Error: 

### ISSUE THREAD

**Issue by cemusta** [XiaoFaye/WooCommerce.NET#86]
Hi,

Wordpress version 4.7.2, WooCommerce version 2.6.13 and WooCommerce.NET version is 0.6.1

I've encountered this problem when I tried to use Bundling plugins to bundle products together. Code gives deserialize exception inside GetProducts

                //init
                RestAPI rest = new RestAPI(restApiUri, ckey, csecret);
                WCObject wc = new WCObject(rest);

                //Get all products
                var products = await wc.GetProducts(); //exception here...

There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.Product, WooCommerceNET, Version=0.5.6.0, Culture=neutral, PublicKeyToken=null]]. Encountered unexpected character '<'.

**Also Nuget version 0.6.1 seems to have version Id of 0.5.6**

**Comment by cemusta** [comment]
This also gives same error when I used a product with product data as Grouped Product.

![image](https://cloud.githubusercontent.com/assets/8707852/22509617/8a3f8476-e897-11e6-8da4-31e19d0d857e.png)

**Comment by XiaoFaye** [comment]
Could you please send me the url and a set of read-only api for testing? xiaofaye(at)msn.com

**Comment by fducharme** [comment]
I had the same problem. Turns out I had wp_debug on. This line in wp-config.php : `define('WP_DEBUG', true); `. Basically the problem is that warning/error messages containing html characters liek '<' were getting returned into the api call response.

**Comment by pcornelio** [comment]
> Hi Xiao! How are you?
> 
> First, I want to congratulate for this great component! You have done a really good job. Thanks for letting us download for free!
> 
> If you allowed me, I want to report a bug or (an error from me but that I don´t know how to solve it).
> 
> When I update the products in range I get the Encountered unexpected character '<'. exception.
> 
> I realized that if I send the description of the product in HTML format I get the exception but now I´m not sending it and I get the same error. The strange thing is that if I create the product I don´t get the exception.
> 
> Thank you very much in advanced,
> Ignacio.

I have same problem.

When I execute GET or UpdateRange (create, update or delete) with  WooCommerce.NET version is 0.8.3

02:33:03 ArticuloDAO > eliminarArticulosSAPAsync() > Error al deserializar el objeto del tipo WooCommerceNET.Base.BatchObject`1[[WooCommerceNET.WooCommerce.v3.Product, WooCommerce.NET, Version=0.8.3.0 Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. Carácter inesperado '<'."}
---------------------------------
I think it is because I am updating the price

![image](https://user-images.githubusercontent.com/10456680/126894517-ff7bab05-fea3-46f6-978b-0605901e51f3.png)

Help me, please.
Thx
